---
namespace: "sceptyre"
name: "ansible_umbrella"
description: "Module for interacting with Cisco Umbrella"

version: "0.0.1"
readme: "README.md"
authors:
    - "Abdellah Fytahi"
license:
    - "MIT"
repository: "https://www.github.com/Sceptyre/ansible-umbrella"
